name: Semantic Release

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - test
      - dev

jobs:
  build:
    name: checkout-version
    if: ${{ github.actor != 'dependabot' }}
    runs-on: ubuntu-latest

    steps:
      - name: Echo actor
        run: |
          echo ${{ github.actor }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
          token: ${{ secrets.DEVOPS_CHANGELOG_TOKEN }}

      - name: Branch protection OFF
        uses: octokit/request-action@v2.x
        if: always()
        with:
          route: PUT /repos/:repository/branches/${{github.ref}}/protection
          repository: ${{ github.repository }}
          required_pull_request_reviews: |
            null
          enforce_admins: |
            null
          required_status_checks: |
            null
          restrictions: |
            null
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_CHANGELOG_TOKEN }}

      - name: Semantic release / Changelog
        id: semantic-release
        run: |
          template="all"
          branch_name=${{ github.ref }}
          repo_name=${{ github.event.repository.name }}
          user_name=${{ github.actor }}
          user_email="${{ github.actor }}@coolbitx.com"
          pr_id="${{ github.event.pull_request.number }}"
          token=${{ secrets.DEVOPS_CHANGELOG_TOKEN }}
          git config --global user.email "devops.g@coolbitx.com"
          git config --global user.name "cbx-devops"
          git config remote.origin.url "https://cbx-devops:$token@github.com/CoolBitX-Technology/$repo_name.git"
          curl -H "Authorization: token $token" -H 'Accept: application/vnd.github.v3.raw' -L https://api.github.com/repos/CoolBitX-Technology/devops-semantic-release/contents/changelog.sh | bash -s -- run $repo_name $branch_name $user_name $user_email $pr_id $template $token

      - name: Branch protection ON
        uses: octokit/request-action@v2.x
        if: always()
        with:
          route: PUT /repos/:repository/branches/${{github.ref}}/protection
          repository: ${{ github.repository }}
          mediaType: |
            previews:
              - luke-cage
          enforce_admins: |
            null
          required_status_checks: |
            null
          restrictions: |
            null
          allow_force_pushes: |
            null
          required_pull_request_reviews: |
            dismissal_restrictions: { "users": ["cbx-devops", "tech-sygna"] }
            dismiss_stale_reviews: true
            required_approving_review_count: 2
        env:
          GITHUB_TOKEN: ${{ secrets.DEVOPS_CHANGELOG_TOKEN }}
